# Generated by Django 4.2.5 on 2023-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='название')),
                ('slhead', models.CharField(max_length=60, verbose_name='заголовок слайдера')),
                ('sltxt', models.CharField(max_length=160, verbose_name='Текст слайдера')),
                ('slp', models.TextField(verbose_name='параграф слайдера')),
            ],
        ),
    ]
