# Generated by Django 4.2.5 on 2023-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mainpage_slimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='slimage',
            field=models.ImageField(upload_to='static/main/images/banner/'),
        ),
    ]
