# Generated by Django 4.2.5 on 2023-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mainpage_slimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slidemainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='название')),
                ('slhead', models.CharField(max_length=60, verbose_name='заголовок слайдера')),
                ('slp', models.TextField(verbose_name='параграф слайдера')),
                ('slimage', models.ImageField(upload_to='static/main/images/banner/')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Записи главной страницы',
            },
        ),
        migrations.DeleteModel(
            name='Mainpage',
        ),
    ]
