# Generated by Django 4.2.5 on 2023-09-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=5, verbose_name='стоимость')),
                ('description', models.CharField(max_length=20, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Соимость',
                'verbose_name_plural': 'Цена',
            },
        ),
    ]
