# Generated by Django 4.2.5 on 2023-09-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='yellow',
            field=models.CharField(choices=[('y', 'Да'), ('m', 'Нет')], default='y', max_length=1),
        ),
    ]
