# Generated by Django 4.2.5 on 2023-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_prices_yellow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='yellow',
            field=models.BooleanField(default='none', verbose_name='Жёлтый'),
        ),
    ]
