# Generated by Django 4.2.5 on 2023-09-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_prices_yellow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='cost',
            field=models.CharField(max_length=6, verbose_name='стоимость'),
        ),
    ]
