# Generated by Django 4.2.5 on 2023-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_prices_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='title',
            field=models.CharField(default='АКПП', max_length=4, verbose_name='Программа'),
        ),
    ]
