# Generated by Django 4.2.5 on 2023-09-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_prices_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='title',
            field=models.CharField(default='АКПП', max_length=15, verbose_name='Программа'),
        ),
    ]
