# Generated by Django 4.2.5 on 2023-09-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
